name: treehuggerdave
favicon: null
layout_spectrum: 0.24550624494440854
typography_spectrum: 0.2518304120749235
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49849485023878515
  lightness: 0.9666461318265647
  saturation: 0.6300443077925593
  rhythmicContrast: 0.9064014437608421
purpose: []
